#!/bin/bash

# Fail on command failure, undefined variables, and piped command
# failures, get the package directory
set -euo pipefail
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
PKGDIR=${DIR}/..

cd ${PKGDIR}
exec npx prettier --write "**/*.{ts,tsx,css,scss,html,json,js}"
